### ISSUE TITLE
PickUp nach einmaligem Aufheben gibt NullPointer wieder

### ISSUE THREAD

**Issue by gamerjungexd** [Overscoped-Project/LaunchIt#1]
PickUp nach einmaligem Aufheben gibt folgendes:

MissingReferenceException: The object of type 'GameObject' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.GameObject.GetComponent[T] () (at C:/buildslave/unity/build/Runtime/Export/Scripting/GameObject.bindings.cs:28)
Player.Update () (at Assets/Entities/Player.cs:65)

**Comment by hastgt** [comment]
behoben durch remove nun nach dem aufheben
