### ISSUE TITLE
Charakter klebt an der Wand

### ISSUE THREAD

**Issue by Hunter13777** [Overscoped-Project/LaunchIt#2]
Wenn der Charakter an einer Wand steht, hat er Probleme von der Wand wegzukommen

**Comment by gamerjungexd** [comment]
Boolean muss entfernt werden. Wird beim nächsten Mergen untersucht ob überhaupt noch nötig, da Bewegung umgestellt auf veloctiy wurde um "Mini"Teleportationen zu vermeiden.

**Comment by gamerjungexd** [comment]
Fixed. Booleans sind entfernt
