### ISSUE TITLE
Projektile ändern Geschwindigkeit

### ISSUE THREAD

**Issue by Hunter13777** [Overscoped-Project/LaunchIt#4]
Die Geschwindigkeit der Projektile variiert.

**Comment by gamerjungexd** [comment]
Noted. Meist ist dies nach dem Start der erste Schuss.

Ist aufgefallen ob dies nach anderen bestimmten Aktionen auch aufgetreten ist?
Weiter gelaufen? In eine bestimmte Richtung geschaut?

**Comment by gamerjungexd** [comment]
Time.deltaTime hat ein zu großen Multiplikator gegeben.
