### ISSUE TITLE
Projektile zerstören sich gegenseitig

### ISSUE THREAD

**Issue by Hunter13777** [Overscoped-Project/LaunchIt#5]
Projektile sollten sich nicht gegenseitig zerstören.

**Comment by gamerjungexd** [comment]
Designfrage. Bitte abklären was genau Projektile zerstören sollen. Sollen diese alles was schaden nehmen kann schaden machen? Sollten Sie sich gegenseitig ignorieren? (in hinblick auf feindliche projektile) Sollten Projektile auch eigene zerstören dürfen?(Theoretisch nie der fall wenn die geschwindigkeit gleich bleibt[Bug bekannt])

**Comment by Hunter13777** [comment]
Projektile des Spielers sollten:
- nur den Gegnern Schaden zufügen
- durch andere Projektile des Spielers durchfliegen
- dem Spieler selbst keinen Schaden zufügen

Falls die Gegner schießen sollten, sollen Projektile der Gegner:
- dem Spieler Schaden zufügen
- über die anderen Gegner drüber fliegen
- durch Projektile anderer Gegner durchfliegen
- bei Kontakt mit einem Projektil des Spielers, sich gegenseitig zerstören

**Comment by gamerjungexd** [comment]
Schaden am Spieler aus #6 hier mit bearbeiten
