### ISSUE TITLE
Projektile machen dem Spieler Schaden

### ISSUE THREAD

**Issue by Hunter13777** [Overscoped-Project/LaunchIt#6]
Projektile sollten dem Spieler keinen Schaden zufügen.

**Comment by gamerjungexd** [comment]
Designfrage. Sollten Projektile jedem Schaden zufügen? Sollen diese nur anderen außer sich selbst Schaden zufügen oder nur bestimmten Objekten?

**Comment by Hunter13777** [comment]
https://github.com/Overscoped-Project/LaunchIt/issues/5

**Comment by gamerjungexd** [comment]
Wird in #5 bearbeitet
